# Generated by Django 5.2.6 on 2025-09-28 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("politics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("answers", models.JSONField(default=dict)),
                ("x", models.FloatField(default=0.0)),
                ("y", models.FloatField(default=0.0)),
            ],
        ),
    ]
