# Generated by Django 5.2.6 on 2025-09-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("politics", "0002_testsubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="label",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("Both", "Both"),
                    ("Neither", "Neither"),
                ],
                max_length=10,
            ),
        ),
    ]
